name: Testing Actions Workflow
on:
  - push
jobs:
  run-github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: "Mona the Octocat"
      - name: Log Greeting Time
        run: echo ${{steps.greet.outputs.time()}}
